server:
  port: 9393
management:
  contextPath: /management
security:
  basic:
    enabled: false
localRepository: ${user.home}${file.separator}.m2${file.separator}repository
remoteRepository: https://repo.spring.io/libs-snapshot
